REM Petvaders v1
REM Recreation of the classic arcadegame "space invaders" in XC-BASIC
REM for the Commodore PET
REM Chris Garrett 2026
REM RetroGameCoders.com
REM ========================================================

REM SCREEN ADDRESS SO MORE PORTABLE
CONST SCREENADDRESS = 32768

REM low byte of system clock
DIM LASTTICK AS BYTE


REM BADDIES:
TYPE ALIEN
  X AS INT
  Y AS INT
  STATE AS INT
  BULLETX AS INT
  BULLETY AS INT
  BULLETSTATE AS INT
END TYPE

REM INITIALISE
DIM LIVES AS INT: LIVES=3
DIM X AS INT
DIM Y AS INT
DIM OLDX AS INT
DIM OLDY AS INT
DIM BX AS INT
DIM BY AS INT
DIM BF AS INT
DIM FAST IDX AS BYTE
DIM AL AS INT
X=10
Y=10
K$=""
GAME_OVER = 0
DIM SCORE AS INT: SCORE=0
DIM HIGH_SCORE AS INT: HIGH_SCORE=0
DIM OLDSCORE AS INT: DIM OLDLIVES AS INT
DIM OLDALIENS AS INT: OLDALIENS=-1
DIM LIVE_CNT AS INT

REM C IS CHARACTER READ FROM THE SCREEN
DIM C AS BYTE: C=32


REM 5 ROWS OF 10 ALIENS
DIM ALIENS_COUNT AS INT: ALIENS_COUNT=50
DIM ALIENS(50) AS ALIEN
DIM FAST ALIEN_LEFT AS INT: ALIEN_LEFT=0
DIM FAST ALIEN_RIGHT AS INT: ALIEN_RIGHT=19
DIM ALIEN_TOP AS INT: ALIEN_TOP=0
DIM ALIEN_BOTTOM AS INT: ALIEN_BOTTOM=8
DIM ALIEN_DIRECTION AS INT: ALIEN_DIRECTION=1

DIM TOP_ALIEN AS BYTE
DIM BOTTOM_ALIEN AS BYTE

REM LEFT, RIGHT, TOP, BOTTOM are the bounds of the alien grid
REM when we move the aliens we use these bounds so we know when
REM to change direction and move down a row.
DIM ROW AS INT
DIM WIDTH AS BYTE
DIM SRC AS WORD
DIM DST AS WORD

REM ALIEN_CHAR is the character to use for the alien (13=M, 23=W)
REM ALIENS SWITCH BETWEEN M AND W ON EACH FRAME

DIM ALIEN_CHAR AS BYTE: ALIEN_CHAR=13
DIM FAST I AS BYTE
DIM FAST A AS BYTE
DIM FAST DIDX AS BYTE


SUB ERASE_ALIENS()

  TMP = SCREENADDRESS+(40*ALIEN_TOP)+ALIEN_LEFT
  WIDTH = ALIEN_RIGHT-ALIEN_LEFT+4
  MEMSET TMP, WIDTH, 32
  TMP = TMP + 80
  MEMSET TMP, WIDTH, 32
  TMP = TMP + 80
  MEMSET TMP, WIDTH, 32
  TMP = TMP + 80
  MEMSET TMP, WIDTH, 32
  TMP = TMP + 80
  MEMSET TMP, WIDTH, 32
  TMP = TMP + 80
  MEMSET TMP, WIDTH, 32

END SUB

SUB INIT_ALIENS()

  ALIENS_COUNT=0
  FOR Y=ALIEN_TOP TO ALIEN_BOTTOM-1 STEP 2
    FOR X=ALIEN_LEFT TO ALIEN_RIGHT-1 STEP 2
      ALIENS(ALIENS_COUNT).X=X
      ALIENS(ALIENS_COUNT).Y=Y
      ALIENS(ALIENS_COUNT).STATE=1
      ALIENS(ALIENS_COUNT).BULLETX=0
      ALIENS(ALIENS_COUNT).BULLETY=0
      ALIENS_COUNT=ALIENS_COUNT+1
    NEXT X
  NEXT Y

END SUB

SUB INITIAL_DRAW()

  REM BASES

  TEXTAT 5,15,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 5,16,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 5,17,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 5,18,CHR$(140)+CHR$(32)+CHR$(140)

  TEXTAT 14,15,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 14,16,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 14,17,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 14,18,CHR$(140)+CHR$(32)+CHR$(140)

  TEXTAT 23,15,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 23,16,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 23,17,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 23,18,CHR$(140)+CHR$(32)+CHR$(140)

  TEXTAT 32,15,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 32,16,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 32,17,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 32,18,CHR$(140)+CHR$(32)+CHR$(140)

END SUB

SUB DROP_ALIENS()
 
  ALIEN_TOP=40
  ALIEN_BOTTOM=-1
 
  FOR DIDX=TOP_ALIEN TO BOTTOM_ALIEN
    IF ALIENS(DIDX).STATE=1 THEN
      ALIENS(DIDX).Y=ALIENS(DIDX).Y+1
      IF ALIENS(DIDX).Y >= ALIEN_BOTTOM THEN 
      	ALIEN_BOTTOM = ALIENS(DIDX).Y
        BOTTOM_ALIEN = DIDX
      END IF
      IF ALIENS(DIDX).Y < ALIEN_TOP THEN 
      	ALIEN_TOP = ALIENS(DIDX).Y
        TOP_ALIEN = DIDX
      END IF
    END IF
  NEXT DIDX

END SUB

SUB MOVE_ALIENS()

  REM Init bounds so min/max are found from living aliens this frame
  ALIEN_LEFT=40
  ALIEN_RIGHT=-1
  FOR IDX=0 TO 49
    IF ALIENS(IDX).STATE=1 THEN
      IF ALIENS(IDX).X<ALIEN_LEFT THEN ALIEN_LEFT=ALIENS(IDX).X
      IF ALIENS(IDX).X>ALIEN_RIGHT THEN ALIEN_RIGHT=ALIENS(IDX).X
      IF ALIENS(IDX).Y<ALIEN_TOP THEN ALIEN_TOP=ALIENS(IDX).Y
      IF ALIENS(IDX).Y>ALIEN_BOTTOM THEN ALIEN_BOTTOM=ALIENS(IDX).Y
    END IF
  NEXT IDX


  IF ALIEN_LEFT<=2 AND ALIEN_DIRECTION=-1 THEN 
   ALIEN_DIRECTION=1

   CALL ERASE_ALIENS()
   CALL DROP_ALIENS()

  END IF
  IF ALIEN_RIGHT>=36 AND ALIEN_DIRECTION=1 THEN 
   ALIEN_DIRECTION=-1
   CALL ERASE_ALIENS()
   CALL DROP_ALIENS()
  END IF

  FOR IDX=0 TO 49
    IF ALIENS(IDX).STATE=1 THEN
	ALIENS(IDX).X=ALIENS(IDX).X+ALIEN_DIRECTION
    END IF
    
    TEXTAT ALIEN_LEFT,ALIEN_TOP,"  m w m w m w m w m w  "
    TEXTAT ALIEN_LEFT,ALIEN_TOP+2,"  m w m w m w m w m w  "
    TEXTAT ALIEN_LEFT,ALIEN_TOP+4,"  m w m w m w m w m w  "
    TEXTAT ALIEN_LEFT,ALIEN_TOP+6,"  m w m w m w m w m w  "
    TEXTAT ALIEN_LEFT,ALIEN_TOP+8,"  m w m w m w m w m w  "

  NEXT IDX

END SUB


REM BULLET MOVEMENT
SUB PLAYER_SHOT()


    REM ERASE PREVIOUS BULLET
    POKE SCREENADDRESS+(40*BY)+BX,32
            TEXTAT 0,0, "                             "

    IF BY >= 0 THEN 
	BY=BY-1
    
        FOR THIS_ALIEN AS INT = 49 TO 0 STEP-1

        TEXTAT 0,0, " b:" + STR$(BX) + " " + STR$(BY) + " a:" +STR$(THIS_ALIEN) + " xy:"+STR$(ALIENS(THIS_ALIEN).X)  + " " +  STR$(ALIENS(THIS_ALIEN).Y)

          IF BY=ALIENS(THIS_ALIEN).Y AND BX=ALIENS(THIS_ALIEN).X THEN
            ALIENS(THIS_ALIEN).STATE=0
            SCORE=SCORE+10
            ALIENS_COUNT=ALIENS_COUNT-1 
            BF=0

            IF ALIENS_COUNT<=0 THEN 
              GAME_OVER=1
            ELSE
              TEXTAT 0,23,"score:"+STR$(SCORE)+" lives:"+STR$(LIVES)+" high:"+STR$(HIGH_SCORE)+" aliens:"+STR$(ALIENS_COUNT)
            END IF

          END IF         
         NEXT THIS_ALIEN

      POKE SCREENADDRESS+(40*BY)+BX,34
    ELSE 
    	BF=0
    END IF


END SUB


REM INFINITE LOOP FOR THE GAME OUTER LOOP 
DO WHILE 1

REM SCREEN
PRINT CHR$(147);CHR$(142)
PRINT "{13}petvaders"
PRINT "chris garrett 2026{13}retrogamecoders.com"
PRINT "{13}{13}press a key to play"
K$=""
DO WHILE K$=""
  GET K$
LOOP
PRINT CHR$(147);


REM RESET THE PLAYER AND GAME VARIABLES
LIVES=3: GAME_OVER=0: SCORE=0: BF=0: BX=0: BY=0
OLDSCORE=-1: OLDLIVES=-1: OLDALIENS=-1
ALIEN_DIRECTION=1: ALIEN_LEFT=12: ALIEN_RIGHT=ALIEN_LEFT+20
ALIEN_TOP=1: ALIEN_BOTTOM=10
TOP_ALIEN=0: BOTTOM_ALIEN=49

CALL INIT_ALIENS()
CALL INITIAL_DRAW()

REM PLAYER START POSITIONS
X=20: Y=20
POKE SCREENADDRESS+(40*Y)+X,65
TEXTAT 0,24,"score:"+STR$(SCORE)+" lives:"+STR$(LIVES)+" high:"+STR$(HIGH_SCORE)+" aliens:"+STR$(ALIENS_COUNT)
    
  REM GAMEPLAY LOOP
  DO WHILE GAME_OVER <> 1 AND LIVES > 0
  
    REM Erase bullet from alien rows before MEMCPY so it won't get copied (prevents trails)
    IF BF=1 THEN POKE SCREENADDRESS+(40*BY)+BX,32
    
    REM PLAYER MOVEMENT 
    OLDX=X
    OLDY=Y
    

    REM '
    GET K$
    IF K$="Q" OR K$="q" THEN
      LIVES=0 
      GAME_OVER = 1
    END IF
    IF K$="D" OR K$="d" THEN X=X+1
    IF K$="A" OR K$="a" THEN X=X-1
    IF K$=" " AND BF=0 THEN 
      BX=X
      BY=Y-1
      BF=1
    END IF
    
    IF PEEK(SCREENADDRESS+(40*Y)+X)<>32 OR X<0 OR X>39 THEN
      X=OLDX
      Y=OLDY
    END IF

          
    IF OLDX<>X OR OLDY<>Y THEN 
      POKE SCREENADDRESS+(40*OLDY)+OLDX,32
      POKE SCREENADDRESS+(40*Y)+X,65
    END IF

    IF PEEK(143) MOD 20 = 0 THEN CALL MOVE_ALIENS() 

    IF BF=1 THEN CALL PLAYER_SHOT()

  LOOP

REM GAME OVER SCREEN
PRINT CHR$(147)


IF LIVES <=0 THEN 
    PRINT "game over!"
ELSE 
    PRINT "you win!"
END IF

IF SCORE > HIGH_SCORE THEN 
  HIGH_SCORE = SCORE
  PRINT "new high score!"
  PRINT "score: ";SCORE

ELSE
 PRINT "score: ";SCORE
 PRINT "high score: ";HIGH_SCORE
END IF
PRINT "press a key to continue"
K$=""
DO WHILE K$=""
  GET K$
LOOP

REM OUTER LOOP FOR THE GAME
LOOP
