REM BADDIES:
TYPE ALIEN
  X AS INT
  Y AS INT
  STATE AS INT
  BULLETX AS INT
  BULLETY AS INT
  BULLETSTATE AS INT
END TYPE

REM INITIALISE
DIM X AS INT
DIM Y AS INT
DIM OLDX AS INT
DIM OLDY AS INT
DIM BX AS INT
DIM BY AS INT
DIM BF AS INT
X=10
Y=10
K$=""
GAME_OVER = 0

REM SCREEN
PRINT CHR$(147);CHR$(142)
POKE 32768+(40*Y)+X,65

REM 5 ROWS OF 10 ALIENS
DIM ALIENS(50) AS ALIEN
DIM ALIEN_LEFT AS INT: ALIEN_LEFT=0
DIM ALIEN_RIGHT AS INT: ALIEN_RIGHT=19
DIM ALIEN_TOP AS INT: ALIEN_TOP=0
DIM ALIEN_BOTTOM AS INT: ALIEN_BOTTOM=4
DIM ALIEN_DIRECTION AS INT: ALIEN_DIRECTION=1
REM LEFT, RIGHT, TOP, BOTTOM are the bounds of the alien grid
REM when we move the aliens we use these bounds so we know when
REM to change direction and move down a row. 


REM column stride: 2 = one space between columns, 3 = two spaces, etc.
DIM COL_STRIDE AS INT: COL_STRIDE=2

REM ALIENS SWITCH BETWEEN M AND W ON EACH FRAME
DIM FAST I AS BYTE
FOR I=0 TO 49
  ALIENS(I).X=(I MOD 10)*COL_STRIDE
  ALIENS(I).Y=I / 10
  ALIENS(I).STATE=1
  ALIENS(I).BULLETX=0
  ALIENS(I).BULLETY=0
  POKE 32768+(40*ALIENS(I).Y)+ALIENS(I).X,13
NEXT I



DO WHILE GAME_OVER <> 1

  OLDX=X
  OLDY=Y
  
  GET K$
  IF K$="Q" OR K$="q" THEN GAME_OVER = 1
  IF K$="D" OR K$="d" THEN X=X+1
  IF K$="A" OR K$="a" THEN X=X-1
  IF K$="W" OR K$="w" THEN Y=Y-1
  IF K$="S" OR K$="s" THEN Y=Y+1
  IF K$=" " THEN 
  	BX=X
	BY=Y-1
  	BF=1
  END IF
  
  IF PEEK(32768+(40*Y)+X)<>32 THEN
  	X=OLDX
  	Y=OLDY
  END IF

        
  IF OLDX<>X OR OLDY<>Y THEN 
  	POKE 32768+(40*OLDY)+OLDX,32
  	POKE 32768+(40*Y)+X,65
  END IF

  IF BF=1 THEN
  	POKE 32768+(40*BY)+BX,32

        IF BY >= 0 THEN 
        	BY=BY-1
  	ELSE 
        	BF=0
        END IF

	IF PEEK(32768+(40*BY)+BX)<>32 THEN 
        	POKE 32768+(40*BY)+BX,32
        	BF=0 
	ELSE
	  	POKE 32768+(40*BY)+BX,34
        END IF
  END IF
LOOP
