REM Petvaders v1.4
REM Recreation of the classic arcadegame "space invaders" in XC-BASIC
REM for the Commodore PET
REM Chris Garrett 2026
REM RetroGameCoders.com
REM ========================================================

REM SCREEN ADDRESS SO MORE PORTABLE
CONST SCREENADDRESS = 32768

REM RANDOM SEED
DIM SEED AS LONG

REM INITIALISE
DIM FAST LIVES AS INT: LIVES=3
DIM FAST X AS INT
DIM FAST Y AS INT
DIM FAST BX AS INT
DIM FAST BY AS INT
DIM FAST BF AS INT
X=10
Y=10
K$=""
DIM FAST GAME_OVER AS BYTE
GAME_OVER = 0
DIM FAST SCORE AS INT: SCORE=0
DIM FAST HIGH_SCORE AS INT: HIGH_SCORE=0

REM C IS CHARACTER READ FROM THE SCREEN
DIM FAST C AS BYTE: C=32
DIM FAST CH AS BYTE: CH=32

REM 5 ROWS OF 10 ALIENS
DIM FAST ALIENS_COUNT AS INT
DIM FAST ALIEN_LEFT AS INT
DIM FAST ALIEN_RIGHT AS INT
DIM FAST ALIEN_TOP AS INT
DIM FAST ALIEN_BOTTOM AS INT
DIM FAST ALIEN_DIRECTION AS INT: ALIEN_DIRECTION=1
DIM FAST CURRENT_ALIEN_ROW AS INT
DIM FAST ROW_EMPTY AS BYTE
DIM FAST ROWS_EMPTY(6) AS BYTE

DIM FAST COL_LEFT AS INT
DIM FAST COL_RIGHT AS INT
DIM FAST STR_OFF AS INT
DIM FAST NUM_COLS AS INT
DIM FAST ALIEN_SHOOTING AS BYTE: ALIEN_SHOOTING=0
DIM FAST ALIEN_MX AS INT: REM MISSILE X
DIM FAST ALIEN_MY AS INT: REM MISSILE Y
DIM I AS INT

REM fake system clock for the alien movement
DIM FAST GAME_TICK AS INT
DIM FAST ALIEN_DELAY AS INT
DIM FAST ALIEN_SHOOT_DELAY AS INT
DIM FAST BULLET_DELAY AS INT
DIM FAST BULLET_TICK AS INT
DIM FAST ALIEN_SHOOT_TICK AS INT

REM FOR DISPLAYING ALIENS (5 rows of 10 aliens)
DIM ALIEN_ROW(6) AS STRING * 23


REM when we move the aliens we use these bounds 
REM to change direction and move down a row.
DIM FAST WIDTH AS BYTE
DIM FAST STR_LINE$ AS STRING * 40
STR_LINE$ = "                                        "

REM DISPLAY THE HUD
SUB HUD()

  TEXTAT 0,0,"score:"+STR$(SCORE)+" lives:"+STR$(LIVES)+" high:"+STR$(HIGH_SCORE)+" aliens:"+STR$(ALIENS_COUNT)+"   "

END SUB

REM ERASE THE ALIENS
SUB ERASE_ALIENS()

  WIDTH = ALIEN_RIGHT-ALIEN_LEFT+4
  IF ROWS_EMPTY(1)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP,LEFT$(STR_LINE$,WIDTH)
  IF ROWS_EMPTY(2)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+2,LEFT$(STR_LINE$,WIDTH)
  IF ROWS_EMPTY(3)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+4,LEFT$(STR_LINE$,WIDTH)
  IF ROWS_EMPTY(4)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+6,LEFT$(STR_LINE$,WIDTH)
  IF ROWS_EMPTY(5)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+8,LEFT$(STR_LINE$,WIDTH)

END SUB

REM DRAW THE ALIENS
SUB DRAW_ALIENS()

  WIDTH = ALIEN_RIGHT-ALIEN_LEFT+4

  IF ROWS_EMPTY(1)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP,LEFT$(ALIEN_ROW(1),WIDTH)
  IF ROWS_EMPTY(2)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+2,LEFT$(ALIEN_ROW(2),WIDTH)
  IF ROWS_EMPTY(3)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+4,LEFT$(ALIEN_ROW(3),WIDTH)
  IF ROWS_EMPTY(4)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+6,LEFT$(ALIEN_ROW(4),WIDTH)
  IF ROWS_EMPTY(5)=0 THEN TEXTAT ALIEN_LEFT-1,ALIEN_TOP+8,LEFT$(ALIEN_ROW(5),WIDTH)

END SUB

REM INITIALIZE THE ALIENS
SUB INIT_ALIENS()

  FOR I=1 TO 5
    ROWS_EMPTY(I)=0
  NEXT I

  ALIENS_COUNT=50
  ALIEN_ROW(1) = " m w m w m w m w m w "
  ALIEN_ROW(2) = " m w m w m w m w m w "
  ALIEN_ROW(3) = " m w m w m w m w m w "
  ALIEN_ROW(4) = " m w m w m w m w m w "
  ALIEN_ROW(5) = " m w m w m w m w m w "


END SUB

REM INITIAL DRAW OF THE PLAYER, HUD AND ALIENS
SUB INITIAL_DRAW()

  REM BASES
  TEXTAT 5,19,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 5,20,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 5,21,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 5,22,CHR$(140)+CHR$(32)+CHR$(140)

  TEXTAT 14,19,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 14,20,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 14,21,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 14,22,CHR$(140)+CHR$(32)+CHR$(140)

  TEXTAT 23,19,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 23,20,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 23,21,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 23,22,CHR$(140)+CHR$(32)+CHR$(140)

  TEXTAT 32,19,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 32,20,CHR$(140)+CHR$(140)+CHR$(140)
  TEXTAT 32,21,CHR$(140)+CHR$(32)+CHR$(140)
  TEXTAT 32,22,CHR$(140)+CHR$(32)+CHR$(140)

  REM HUD
  CALL HUD()

  REM DRAW THE ALIENS
  CALL DRAW_ALIENS()

END SUB

REM WAIT FOR A KEY TO BE PRESSED
SUB WAIT_KEY()

  DIM KEY$ AS STRING * 1
  KEY$=""
  DO WHILE KEY$=""
    GET KEY$
  LOOP

END SUB


REM DROP THE ALIENS DOWN A ROW
SUB DROP_ALIENS()
 
  ALIEN_TOP=ALIEN_TOP + 1
  ALIEN_BOTTOM=ALIEN_BOTTOM + 1

  IF ALIEN_BOTTOM > 22 THEN 
  	GAME_OVER = 1
        LIVES = 0
  END IF

END SUB

REM MOVE THE ALIENS LEFT AND RIGHT
SUB MOVE_ALIENS()


  REM UPDATE THE ALIEN BOUNDS
  ALIEN_LEFT=ALIEN_LEFT+ALIEN_DIRECTION
  ALIEN_RIGHT=ALIEN_RIGHT+ALIEN_DIRECTION

  IF ALIEN_LEFT<=2 AND ALIEN_DIRECTION=-1 THEN 
   ALIEN_DIRECTION=1

   CALL ERASE_ALIENS()
   CALL DROP_ALIENS()

  END IF
  IF ALIEN_RIGHT>=38 AND ALIEN_DIRECTION=1 THEN 
   ALIEN_DIRECTION=-1
   CALL ERASE_ALIENS()
   CALL DROP_ALIENS()
  END IF


  REM REDRAW THE ALIENS
  CALL DRAW_ALIENS()
  
END SUB

REM CHECK WHICH ALIEN HAS BEEN KILLED
SUB KILL_ALIEN()

DIM TMPS$ AS STRING * 32

    REM DISABLE THE BULLET
    BF=0

    REM ERASE THE ALIEN FROM THE ROW AND SCREEN
    CURRENT_ALIEN_ROW=((BY-ALIEN_TOP)/2)+1
    POKE @ALIEN_ROW(CURRENT_ALIEN_ROW) + BX-ALIEN_LEFT+2, 32
    POKE SCREENADDRESS+(40*BY)+BX,42
  
    REM if bottom row is now all spaces, move ALIEN_BOTTOM up
    IF BY=ALIEN_BOTTOM THEN 
      ROW_EMPTY=1
      FOR I=1 TO 19 STEP 2
        IF PEEK(@ALIEN_ROW(CURRENT_ALIEN_ROW)+1+I)<>32 THEN 
          ROW_EMPTY=0
        END IF

      NEXT I
      ROWS_EMPTY(CURRENT_ALIEN_ROW)=ROW_EMPTY

      DO WHILE ROW_EMPTY=1 AND ALIEN_BOTTOM>ALIEN_TOP
        ALIEN_BOTTOM=ALIEN_BOTTOM-2
        CURRENT_ALIEN_ROW=CURRENT_ALIEN_ROW-1
        IF CURRENT_ALIEN_ROW>=1 THEN
          ROW_EMPTY=1
          FOR I=1 TO 19 STEP 2
            IF PEEK(@ALIEN_ROW(CURRENT_ALIEN_ROW)+1+I)<>32 THEN ROW_EMPTY=0
          NEXT I
        ELSE
          ROW_EMPTY=0
        END IF
      LOOP
    END IF

    REM only check the column we just hit - use same offset as POKE (BX-ALIEN_LEFT+2)
    REM left column: offset 2, right column: offset ALIEN_RIGHT-ALIEN_LEFT+2
    IF BX=ALIEN_LEFT AND COL_LEFT<COL_RIGHT THEN
      COL_EMPTY=1
      STR_OFF=1+COL_LEFT
      IF PEEK(@ALIEN_ROW(1)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(2)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(3)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(4)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(5)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF COL_EMPTY=1 THEN 

          WIDTH = ALIEN_RIGHT-ALIEN_LEFT+4
          TEXTAT ALIEN_LEFT-1,ALIEN_TOP,LEFT$(STR_LINE$,WIDTH)
          TMPS$=MID$(ALIEN_ROW(1),2,20) + "  "
          ALIEN_ROW(1)=TMPS$

          TMPS$=MID$(ALIEN_ROW(2),2,20) + "  "
          ALIEN_ROW(2)=TMPS$

          TMPS$=MID$(ALIEN_ROW(3),2,20) + "  "
          ALIEN_ROW(3)=TMPS$

          TMPS$=MID$(ALIEN_ROW(4),2,20) + "  "
          ALIEN_ROW(4)=TMPS$

          TMPS$=MID$(ALIEN_ROW(5),2,20) + "  "
          ALIEN_ROW(5)=TMPS$
          ALIEN_LEFT=ALIEN_LEFT+2
          CALL DRAW_ALIENS()
      END IF
    END IF

    REM if right column now empty, move left
    IF BX=ALIEN_RIGHT AND COL_LEFT<COL_RIGHT THEN
      COL_EMPTY=1
      STR_OFF=ALIEN_RIGHT-ALIEN_LEFT+2
      IF PEEK(@ALIEN_ROW(1)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(2)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(3)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(4)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF PEEK(@ALIEN_ROW(5)+STR_OFF)<>32 THEN COL_EMPTY=0
      IF COL_EMPTY=1 THEN COL_RIGHT=COL_RIGHT-2 : ALIEN_RIGHT=ALIEN_RIGHT-2
    END IF

  

    REM INCREASE THE SCORE AND CHECK IF THE GAME IS OVER
    SCORE=SCORE+10
    ALIENS_COUNT=ALIENS_COUNT-1
    IF ALIENS_COUNT<=0 THEN GAME_OVER=1

    REM UPDATE THE HUD WITH THE NEW SCORE AND ALIENS COUNT
    CALL HUD()


END SUB

REM BULLET MOVEMENT
SUB PLAYER_FIRING()
  
    REM CHECK IF THE BULLET HAS HIT THE TOP OF THE ALIEN ROW
    IF BY <= ALIEN_TOP THEN

      REM ERASE THE BULLET FROM THE SCREEN
    	POKE SCREENADDRESS+(40*BY)+BX,32
    	BF=0
        RETURN 
    ELSE

      REM MOVE THE BULLET UP A ROW
      POKE SCREENADDRESS+(40*BY)+BX,32
      BY=BY-1

      REM CHECK IF THE BULLET HAS HIT ANYTHING
      C=PEEK(SCREENADDRESS+(40*BY)+BX)
      IF C=204 THEN BF=0:POKE SCREENADDRESS+(40*BY)+BX,32
      IF C=32 THEN POKE SCREENADDRESS+(40*BY)+BX,34

      REM CHECK IF THE BULLET HAS HIT AN ALIEN
      IF C=13 OR C=23 THEN CALL KILL_ALIEN()
        
    END IF
END SUB

REM PLAYER EXPLOSION ANIMATION
SUB PLAYER_EXPLOSION()

  FOR I=0 TO 5
    TEXTAT X,Y,"*"
    TEXTAT X-1,Y,"*"
    TEXTAT X+1,Y,"*"
    TEXTAT X,Y-1,"*"

    FOR ALIEN_SHOOT_TICK=0 TO 1000
      REM NOP
    NEXT 
    TEXTAT X,Y," "
    TEXTAT X-2,Y,"*"
    TEXTAT X+2,Y,"*"
    TEXTAT X,Y-2,"*"

    FOR ALIEN_SHOOT_TICK=0 TO 1000
      REM NOP
    NEXT 
    TEXTAT X,Y,"*"
    TEXTAT X-1,Y,"*"
    TEXTAT X+1,Y,"*"
    TEXTAT X,Y-1,"*"

    FOR ALIEN_SHOOT_TICK=0 TO 1000
      REM NOP
    NEXT 
    TEXTAT X-1,Y," "
    TEXTAT X+1,Y," "
    TEXTAT X,Y-1," "
    TEXTAT X,Y+1," "
    TEXTAT X,Y,"*"
    TEXTAT X-1,Y-1,"*"
    TEXTAT X+1,Y-1,"*"
    TEXTAT X,Y-1,"*"

    REM DELAY FOR THE ANIMATION
    FOR ALIEN_SHOOT_TICK=0 TO 2000
      REM NOP
    NEXT

    TEXTAT X-2,Y," "
    TEXTAT X+2,Y," "
    TEXTAT X,Y-2," "
    TEXTAT X,Y+2," "
    TEXTAT X-1,Y-1," "
    TEXTAT X+1,Y-1," "
    TEXTAT X,Y-1," "
    TEXTAT X,Y+1," "
    TEXTAT X-1,Y," {193} "
  NEXT I

END SUB

REM ALIEN SHOOTING AND COLLISION CHECK
SUB ALIEN_FIRING()
  IF ALIEN_SHOOTING<>1 THEN
   
    REM aliens at ALIEN_LEFT+0,2,4.. (every other column) - pick one within formation
    NUM_COLS=(ALIEN_RIGHT-ALIEN_LEFT)/2+1
    IF NUM_COLS<1 THEN NUM_COLS=1
    ALIEN_MX=ALIEN_LEFT+2*CINT(RND()*NUM_COLS)
    IF ALIEN_MX>39 THEN ALIEN_MX=ALIEN_RIGHT

    REM CHECK IF THERE'S AN ALIEN THERE SO CAN SHOOT (use ALIEN_BOTTOM - bottom row)
    IF PEEK(SCREENADDRESS+(40*ALIEN_BOTTOM)+ALIEN_MX)<>32 THEN 
      ALIEN_SHOOTING=1
      ALIEN_MY=ALIEN_BOTTOM+1
    END IF
  END IF
  
  REM CHECK IF THE ALIEN HAS FIRED A MISSILE
  IF ALIEN_SHOOTING=1 THEN

    TEXTAT ALIEN_MX,ALIEN_MY," " 
    IF ALIEN_MY<24 THEN 
      ALIEN_MY=ALIEN_MY+1
    ELSE
      ALIEN_SHOOTING=0
      REM CHECK IF THE ALIEN MISSILE HAS HIT THE PLAYER
      IF ALIEN_MX=X AND ALIEN_MY=Y THEN 
        LIVES=LIVES-1
        IF LIVES<1 THEN GAME_OVER=1
        ALIEN_SHOOTING=0

        CALL PLAYER_EXPLOSION()

        CALL HUD() 

        ELSE  
          RETURN
        
      END IF
    END IF

    REM CHECK IF THE ALIEN MISSILE HAS HIT ANYTHING ELSE
    CH=PEEK(SCREENADDRESS+(40*(ALIEN_MY))+ALIEN_MX)
    IF CH=32 THEN TEXTAT ALIEN_MX,ALIEN_MY,"$" 
    IF CH=204 THEN : REM BASE HIT
      ALIEN_SHOOTING=0 
      TEXTAT ALIEN_MX,ALIEN_MY," " 
    END IF
    
    

  END IF


END SUB

REM ATTRACT MODE SCREEN(S) - BASIC RIGHT NOW
SUB WELCOME()

  PRINT CHR$(147);CHR$(142)
  PRINT "{13}petvaders"
  PRINT "chris garrett 2026{13}retrogamecoders.com"
  PRINT "{13}{13}press a key to play"
  CALL WAIT_KEY()
  PRINT CHR$(147);
  SEED=(PEEK(142)*256)+PEEK(143)
  RANDOMIZE SEED

END SUB

REM GAME OVER SCREEN (WIN OR LOSE)
SUB END_SCREEN()
  PRINT CHR$(147)


  IF LIVES <=0 THEN 
      PRINT "game over!"
  ELSE 
      PRINT "you win!"
  END IF

  IF SCORE > HIGH_SCORE THEN 
    HIGH_SCORE = SCORE
    PRINT "new high score!"
    PRINT "score: ";SCORE

  ELSE
   PRINT "score: ";SCORE
   PRINT "high score: ";HIGH_SCORE
  END IF
  PRINT "press a key to continue"
  CALL WAIT_KEY()
  
END SUB

REM INITIALIZE A NEW GAME
SUB INIT_GAME()

  REM RESET THE PLAYER AND GAME VARIABLES
  LIVES=3: GAME_OVER=0: SCORE=0: BF=0: BX=0: BY=0
  ALIEN_DIRECTION=1: ALIEN_LEFT=12: ALIEN_RIGHT=ALIEN_LEFT+18
  COL_LEFT=1: COL_RIGHT=19
  ALIEN_TOP=1: ALIEN_BOTTOM=9: ALIEN_SHOOTING=0: ALIEN_MX=ALIEN_LEFT+3: ALIEN_MY=ALIEN_BOTTOM+1
  ALIEN_DELAY=1000: ALIEN_SHOOT_DELAY=100: BULLET_DELAY=20
  GAME_TICK=0: BULLET_TICK=0: ALIEN_SHOOT_TICK=0: ALIEN_SHOOTING=0

  REM RESET THE ALIENS AND DRAW THE INITIAL ALIEN ROWS
  CALL INIT_ALIENS()
  CALL INITIAL_DRAW()
  
  REM DRAW THE PLAYER
  REM PLAYER START POSITIONS
  X=20: Y=24
  POKE SCREENADDRESS+(40*Y)+X,65
   

END SUB


REM INFINITE LOOP FOR THE GAME OUTER LOOP 
DO WHILE 1

REM WELCOME SCREEN
CALL WELCOME()

REM INITIALIZE THE GAME VARIABLES AND DRAW THE INITIAL ALIEN ROWS
CALL INIT_GAME()

 
  REM MAIN GAMEPLAY LOOP
  DO WHILE GAME_OVER <> 1 AND LIVES > 0
  IF ALIEN_MX>38 THEN PRINT "alien mx:";ALIEN_MX:CALL WAIT_KEY()
    REM CHECK THE KEYBOARD BUFFER
    IF PEEK(158)>0 THEN 

      REM GET THE KEY FROM THE KEYBOARD BUFFER
    	GET K$

      REM CHECK IF THE PLAYER HAS QUIT
      IF K$="Q" OR K$="q" THEN
        LIVES=0 
        GAME_OVER = 1
      END IF
      
      REM CHECK IF THE PLAYER HAS MOVED RIGHT
      IF K$="D" OR K$="d" AND X<39 THEN 
      	X=X+1
        TEXTAT X-1,Y," {193} "
      END IF
      
      REM CHECK IF THE PLAYER HAS MOVED LEFT
      IF K$="A" OR K$="a" AND X>1  THEN 
      	X=X-1
        TEXTAT X-1,Y," {193} "
      END IF
      
      REM CHECK IF THE PLAYER HAS FIRED A BULLET
      REM ONLY FIRE IF THE BULLET IS NOT ALREADY FIRING
      IF K$=" " AND BF=0 THEN 
        BX=X
        BY=Y-1
        BF=1
      END IF


      
    END IF

    REM GAME TICK - use counters not MOD (MOD/division is slow on 6502)
    BULLET_TICK=BULLET_TICK+1
    IF BULLET_TICK>=BULLET_DELAY THEN
      BULLET_TICK=0
      IF BF=1 THEN CALL PLAYER_FIRING()
    END IF
    
    REM ALIEN SHOOTING
    ALIEN_SHOOT_TICK=ALIEN_SHOOT_TICK+1
    IF ALIEN_SHOOT_TICK>=ALIEN_SHOOT_DELAY THEN
      ALIEN_SHOOT_TICK=0
      CALL ALIEN_FIRING()
    END IF

    REM ALIEN MOVEMENT
    GAME_TICK=GAME_TICK+1
    IF GAME_TICK>=ALIEN_DELAY THEN
      CALL MOVE_ALIENS()
      GAME_TICK=0
    END IF

  REM END OF MAIN GAMEPLAY LOOP
  LOOP

  REM GAME OVER SCREEN
  REM DISPLAY THE SCORE, HIGH SCORE AND ALIENS COUNT
  CALL END_SCREEN()

REM END OF OUTER LOOP FOR THE GAME
REM AFTER A KEYPRESS THE GAME WILL RESTART FRESH
LOOP
