REM Petzerk v1.3
REM Recreation of the classic arcadegame "Bezerk" in XC-BASIC for the Commodore PET
REM Chris Garrett 2026
REM RetroGameCoders.com
REM ========================================================

REM SCREEN ADDRESS SO MORE PORTABLE
CONST SCREENADDRESS = 32768

REM TEMP START SCREEN
PRINT CHR$(147);CHR$(142)
K$=""
PRINT "petzerk - press a key to start"
DO WHILE K$=""
 GET K$
LOOP


REM PLAYER:
DIM FAST X AS INT
DIM FAST Y AS INT
DIM FAST OLDX AS INT
DIM FAST OLDY AS INT

REM BULLET:
DIM BX AS INT
DIM BY AS INT
DIM BF AS INT
DIM BOFFSET AS WORD
REM Bullet fires N, S, E or W in the direction the player last moved
DIM BXDIR AS INT 
DIM BYDIR AS INT 
DIM LASTXDIR AS INT
DIM LASTYDIR AS INT


REM ROOM:
DIM ROOM(20, 20) AS BYTE
FOR Y=0 TO 19
  FOR X=0 TO 19
    IF Y=0 OR Y=19 OR X=0 OR X=19 THEN ROOM(Y,X)=230 ELSE ROOM(Y,X)=32
  NEXT X
NEXT Y

REM BOTS:
TYPE BOT
  X AS INT
  Y AS INT
  DIRX AS INT
  DIRY AS INT
  STATE AS INT
  BULLETX AS INT
  BULLETY AS INT
  BULLETXDIR AS INT
  BULLETYDIR AS INT
  BULLETSTATE AS INT
END TYPE
DIM BOTS(10) AS BOT

REM RANDOMLY PLACE 6 BOTS IN THE ROOM:
DIM SEED AS LONG

REM PEEK(142) AND PEEK(143) COMBINE TO MAKE A LONG INTEGER
SEED=(PEEK(142)*256)+PEEK(143)
RANDOMIZE SEED

DIM FAST I AS BYTE
FOR I=0 TO 5
  BOTS(I).X=1+RND()*17
  BOTS(I).Y=1+RND()*17
  BOTS(I).DIRX=RND()
  BOTS(I).DIRY=RND()
  BOTS(I).STATE=0
  ROOM(BOTS(I).Y,BOTS(I).X)=56
NEXT I

REM Draw the room
PRINT CHR$(147);CHR$(142)
FOR Y=0 TO 19
  FOR X=0 TO 19
    POKE SCREENADDRESS+(40*Y)+X,ROOM(Y,X)
  NEXT X
NEXT Y

REM INITIALIZE:
X=6
Y=6
K$=""
GAME_OVER = 0
LASTXDIR=0
LASTYDIR=-1

REM SHOW PLAYER START POSITION:
POKE SCREENADDRESS+(40*Y)+X,38

REM MAIN LOOP:
DO WHILE GAME_OVER <> 1

  OLDX=X
  OLDY=Y
  
  GET K$
  IF K$="Q" OR K$="q" THEN GAME_OVER = 1
  IF K$="D" OR K$="d" THEN X=X+1
  IF K$="A" OR K$="a" THEN X=X-1
  IF K$="W" OR K$="w" THEN Y=Y-1
  IF K$="S" OR K$="s" THEN Y=Y+1
  IF K$=" " THEN 
    BXDIR=LASTXDIR
    BYDIR=LASTYDIR
    BX=X+BXDIR
    BY=Y+BYDIR
  	BF=1
  END IF
  
  IF PEEK(SCREENADDRESS+(40*Y)+X)<>32 THEN
  	X=OLDX
  	Y=OLDY
  END IF

        
  IF OLDX<>X OR OLDY<>Y THEN 
  	LASTXDIR=X-OLDX
  	LASTYDIR=Y-OLDY
  	POKE SCREENADDRESS+(40*OLDY)+OLDX,32
  	POKE SCREENADDRESS+(40*Y)+X,38
  END IF

  IF BF=1 THEN
      REM Erase bullet at current position
      BOFFSET=SCREENADDRESS+(40*BY)+BX
      POKE BOFFSET,32

      IF BY > 1 AND BY < 18 AND BX > 1 AND BX < 18 THEN 
        BY=BY+BYDIR
        BX=BX+BXDIR
        REM Draw bullet at new position only
        BOFFSET=SCREENADDRESS+(40*BY)+BX
        IF PEEK(BOFFSET)<>32 THEN 
          POKE BOFFSET,32
          BF=0 
        ELSE
          POKE BOFFSET,42
        END IF
      ELSE 
        BF=0
      END IF
  END IF
LOOP
